### ISSUE TITLE
Basic documentation for compiling a program to machine code

### ISSUE THREAD

**Issue by honza** [artagnon/rhine-ml#10]
I have a file `main.clj`:

``` clj
(defn main []
  (println "hello"))
```

I compiled it with

```
$ cat main.clj | ./rhine.native
```

And moved the output to `main`.  Then I tried to compile that to `.bc` to with

```
$ llvm-as main -o main.bc
```

But I get

```
/usr/local/opt/llvm/bin/llvm-as: main:7:53: error: invalid indices for getelementptr
  %value = call i8* @malloc(i64 ptrtoint (%value_t* getelementptr (%value_t* null, i32 1) to i64))
```

---

How do you usually compile your code?

**Comment by artagnon** [comment]
That happens because I print the full LLVM IR. But the goal of Rhine is to provide a JIT, not facilitate AOT compilation; when you do:

```
$ ./rhine.native <sample.rh
```

it should run the code automatically. If you need to run a function `foo`, call the function from the toplevel like:

``` clj
(defn foo [] (println "hello"))
(foo)
```

That said, it wasn't automatically matching the name "main" and running the function: I've fixed it now. Your example works.

More documentation is always appreciated! Thanks :)
