### ISSUE TITLE
build error on ubuntu 14.04

### ISSUE THREAD

**Issue by sunilnandihalli** [artagnon/rhine-ml#13]
I am not sure if this is a related issue. But I get the follow when I try to build rhine on ubuntu 14.04. I am only writing here since I could find no other better place to report.
.opam/system/lib/llvm/./dllllvm.so: undefined symbol: LLVMGetFirstUse
make: **\* [rhine] Error 2

**Comment by artagnon** [comment]
Thanks for opening an issue about this. Can you make sure that the version of the llvm package that opam has is 3.5 (do an `opam list llvm`)? If it's out of date, can you `opam update` and `opam upgrade`?

At that point, you should get different build errors because I'm currently working against llvm git HEAD. Once my work is stable, I'll include llvm as a submodule and make it build out-of-the-box.

**Comment by sunilnandihalli** [comment]
my llvm is version 3.5 I still face the same issue.

**Comment by artagnon** [comment]
Can you try again? With my fork of llvm (soon to be upstreamed), everything works fine on Linux and OS X.
